language: android

android:
  components:
# The BuildTools version used by your project
    - build-tools-23.0.2
# The SDK version used to compile your project
    - android-23    
    
# A peculiarity of dependency caching in Gradle means that 
# to avoid uploading the cache after every build you need 
#to add the following lines
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/